# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tDpvefacIjEi8b4IaSDn3RJE4mmKt56S
"""

class Employees():
  def __init__(self, name, age):
        self.name = name
        self.age = age
        self.language = []

  def addLanguage(self,new_lang):
        self.language.append(new_lang)


class Managers(Employees):
  def __init__(self, name, age):
    Employees.__init__(self, name, age)

Employee1 = Employees("Metehan", 24)
Employee1.addLanguage("Turkish")
Employee1.addLanguage("English")


Employee2 = Employees("Beril", 24)
Employee2.addLanguage("Turkish")
Employee2.addLanguage("English")
Employee2.addLanguage("German")

Employee3 = Employees("Oguzhan", 22)
Employee3.addLanguage('Turkish')
Employee3.addLanguage('English')

Manager1 = Managers("Şeref", 56)
Manager1.addLanguage("English")
Manager1.addLanguage("Turkish")

Manager2 = Managers("Meral", 54)
Manager2.addLanguage("Turkish")
Manager2.addLanguage("English")
Manager2.addLanguage("German")

total =(Employee1.language + Employee2.language+ Employee3.language)
total = list(dict.fromkeys(total))
print (total)